
package com.himalaya.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-25T11:31:24.913+08:00
 * Generated source version: 3.1.9
 */

@WebFault(name = "Exception", targetNamespace = "http://service.himalaya.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.himalaya.service.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.himalaya.service.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.himalaya.service.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.himalaya.service.Exception getFaultInfo() {
        return this.exception;
    }
}
