package com.himalaya.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-25T11:31:24.963+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "IServiceService", 
                  wsdlLocation = "http://localhost:8090/himalayaWebService/services/searchService/service?wsdl",
                  targetNamespace = "http://service.himalaya.com/") 
public class IServiceService extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.himalaya.com/", "IServiceService");
    public final static QName IServicePort = new QName("http://service.himalaya.com/", "IServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8090/himalayaWebService/services/searchService/service?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8090/himalayaWebService/services/searchService/service?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IService
     */
    @WebEndpoint(name = "IServicePort")
    public IService getIServicePort() {
        return super.getPort(IServicePort, IService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IService
     */
    @WebEndpoint(name = "IServicePort")
    public IService getIServicePort(WebServiceFeature... features) {
        return super.getPort(IServicePort, IService.class, features);
    }

}
