package com.himalaya.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-01-25T11:31:24.939+08:00
 * Generated source version: 3.1.9
 * 
 */
@WebService(targetNamespace = "http://service.himalaya.com/", name = "IService")
@XmlSeeAlso({ObjectFactory.class})
public interface IService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "parseUser", targetNamespace = "http://service.himalaya.com/", className = "com.himalaya.service.ParseUser")
    @WebMethod
    @ResponseWrapper(localName = "parseUserResponse", targetNamespace = "http://service.himalaya.com/", className = "com.himalaya.service.ParseUserResponse")
    public java.lang.String parseUser(
        @WebParam(name = "user", targetNamespace = "")
        com.himalaya.service.User user
    ) throws Exception_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "service", targetNamespace = "http://service.himalaya.com/", className = "com.himalaya.service.Service")
    @WebMethod
    @ResponseWrapper(localName = "serviceResponse", targetNamespace = "http://service.himalaya.com/", className = "com.himalaya.service.ServiceResponse")
    public java.lang.String service(
        @WebParam(name = "username", targetNamespace = "")
        java.lang.String username
    ) throws Exception_Exception;

    @RequestWrapper(localName = "setUser", targetNamespace = "http://service.himalaya.com/", className = "com.himalaya.service.SetUser")
    @WebMethod
    @ResponseWrapper(localName = "setUserResponse", targetNamespace = "http://service.himalaya.com/", className = "com.himalaya.service.SetUserResponse")
    public void setUser();
}
