CREATE TABLE TB_USERS(
	ID NUMBER(10,0) PRIMARY KEY, 
	USER_NAME VARCHAR2(1000 BYTE), 
	STATUS CHAR(1 BYTE), 
	TYPE CHAR(1 BYTE),
	REGIST_DATE DATE DEFAULT sysdate, 
	LAST_LOGIN_DATE DATE DEFAULT sysdate
);
  
INSERT INTO TB_USERS(ID,USER_NAME, STATUS, TYPE,REGIST_DATE,LAST_LOGIN_DATE)  VALUES(1, 'FRED', 1, 2, SYSDATE, SYSDATE);
INSERT INTO TB_USERS(ID,USER_NAME, STATUS, TYPE,REGIST_DATE,LAST_LOGIN_DATE)  VALUES(2, 'ANNA', 1, 2, SYSDATE, SYSDATE);
INSERT INTO TB_USERS(ID,USER_NAME, STATUS, TYPE,REGIST_DATE,LAST_LOGIN_DATE)  VALUES(3, 'WENDY', 1, 2, SYSDATE, SYSDATE);
COMMIT;